version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: placement_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: placement_portal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: placement_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: placement_portal
      DB_DIALECT: mysql
      JWT_SECRET: supersecretjwtkey123
    depends_on:
      - mysqldb

volumes:
  db_data:
